name: Code Coverage Reporter
# This gets called when ./coverage-report-pull-request.yaml has completed. See that file
# for why this is split into two.
on:
  workflow_run:
    workflows: [ "Code Coverage Builder" ]
    types:
      - completed
jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    name: Code Coverage Reporter
    runs-on: ubuntu-latest
    steps: 
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/api/target/site/jacoco/jacoco.xml,${{ github.workspace }}/runtime/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 75
          debug-mode: true
